---
title: "Thoughts about religious issues"
author: "Sean van der Merwe"
date: 2018-08-14
slug: opinion-religion
categories:
  - opinion
  - religion
tags:
  - opinion
  - religion
---

#### Q: What religion do you follow?

**A:** Every religion on earth has leaders that try to corrupt that religion for their own gain. Sometimes they convince themselves and those around them that they are serving the greater good, but at the same time straying and leading people further from the core faith. It's better to pick a faith and then find a group that follows that faith to the best of their ability.

#### Q: So what faith do you follow?

**A:** I follow Jesus Christ. I believe in his teachings and try to follow the principles he put forth. I trust him to guide and protect my soul.

#### Q: Why?

**A:** When I look at the world around me I see good everywhere, from the tiniest effects of quantum mechanics to the grandest scale of the universe. I see flawed people, including myself, constantly being blessed in ways they do not and cannot deserve through their own actions. If I take even a moment to think of all the ways our world could have turned out worse then I cannot help to be grateful.

To put it another way, I see so much good in the world that doesn't come from the hearts of people, including people being good to each other without reason, but also nature not wiping us all out every day by chance. This good and the wonder of the world can only come from a benevolent creator that is full of such love that the love must be shared. I thus conclude that God created us both as recipients of love and as beings able to appreciate love. 

Then the next question would be, "What would a loving creator need from us?" The obvious answer is *nothing*. The creator doesn't *need* anything from us. Sure, things would go much better for everybody if we all followed God's will exactly, but that will not change God, only bring him joy because he loves us and wants the best for us. In all the religions I've encountered, the only one that truly captures this idea that God needs nothing from us is Christianity.

Core Christianity says that God has given us everything, including salvation from ourselves. We simply need to say, "Thank you", or we can reject it if we like. You have already received everlasting life and love for your eternal soul, just stop rejecting it and you will have a better life both on earth and ever after.

#### Q: What is the meaning of life?

**A:** The meaning of life is gratitude. If you are grateful for your loved ones you will treat them at least as well as you treat yourself. If you are grateful for you job you will do your best each day at work. If you are grateful for your income you will want to share some of it with those who have less. If you are grateful for your time you will make the most of the day. If you are grateful for your health you will try to maintain or improve it into the future.

#### Q: So what about prosperity?

**A:** While there is some correlation between gratitude and happiness, there is no one-to-one relationship between action and consequence. The bible says that even the tiniest wrongdoing theoretically deserves death, but that Jesus came to break that link, thank heavens. The bible does not say that if you do good you will directly receive more goodness back, at least not in this life. It says your actions have impact on the next life. A lot of priests say that you must donate more and more and then you'll be rewarded, but mostly they are just trying to make themselves rich. The bible says to give in secret because you are grateful, not expecting reward or recognition.

#### Q: So why do good?

**A:** Because doing good is the best way to say thank you to the Lord for the love He gives you every day. The love of the Lord empowers us to love those around us and we must be grateful for that gift.

#### Q: What about the contradictions between the bible and science/common sense/etc. ?

**A:** The bible doesn't contradict science, nor common sense, nor any principle that is born of goodness and gratitude. Any such contradiction is the result of people failing to understand the true message God is trying to send us through his Word. God's message can only be understood when the bible is approached with a humble heart, not one that tries to use the bible to support an already twisted viewpoint. 

Science is about trying to understand what we see around us. What we see around us was created by God, thus science is a tool that can help us to understand God better.

Many Christians around the world are judged harshly. Most of this is fear and ignorance. However, some of it is justified because some Christians stick to an arrogant interpretation of the Word even when God tells them clearly that they are mistaken.

#### Q: So what is the right interpretation?

**A:** The one that increases the love in the world and spreads God's love into more hearts.

